# site_name: My Docs

# theme:
#   name: material
#   language: zh-TW
#   palette:
#     - scheme: slate
#       primary: grey
#       accent: lime
#   features:
#     - navigation.instant
#     - navigation.sections
#     - navigation.tabs
#     - toc.integrate
#     - content.code.copy
#     - content.code.annotate

# extra_css:
#   # - styles/industrial.css
#   - styles/slate-dark.css  


site_name: BT hair 比塔時尚
site_url: https://bthair0419.github.io/Bthairsalon/
use_directory_urls: false

nav :
# - Home : index.md
 - 首頁 : index.md
 - 設計師 : 設計師.md
 - 作品 : 作品.md
# - 產品 :  產品.md
 - 官方預約 :  官方預約.md
 - 價目表 : 價目表.md

theme:
  name: readthedocs
  custom_dir: overrides
  logo: image/logo.jpg
  favicon: favicon.ico


plugins: []

extra:
  company_name: "BT hair 比塔時尚"
  company_address: "106 臺北市大安區忠孝東路四段216巷27弄4號"
  company_phone: "0958479319"
  description: "台北大安區專業髮廊，日系剪髮、質感染髮、造型設計、護髮服務。"
  keywords: "台北髮廊, 大安區髮廊, 剪髮推薦, 染髮推薦, BT hair, 設計師"

# 收起首頁 特殊符號 、 logo大小
extra_css:
  - css/custom.css
  - styles/global-center.css
  - styles/hide-expand.css
  - styles/logo-size.css
  - styles/gallery.css
  - styles/video-gallery.css
  - styles/style.css